/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author Josue Ambrocio
 */
public class menuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menuPrincipal.class.getName());

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlTarjeta = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblNombreCondominio = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        pnlBienvenida = new javax.swing.JPanel();
        lblAvatarAdmin = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        lblTituloModulos = new javax.swing.JLabel();
        btnRegistroPropietario = new javax.swing.JButton();
        btnRegistroPago = new javax.swing.JButton();
        btnConfigurarCuota = new javax.swing.JButton();
        btnEstadoCuenta = new javax.swing.JButton();
        btnReporteGeneral = new javax.swing.JButton();
        btnCasasMorosas = new javax.swing.JButton();
        lblTituloResumen = new javax.swing.JLabel();
        pnlCasasTotales = new javax.swing.JPanel();
        lblNumCasasTotales = new javax.swing.JLabel();
        lblDescCasasTotales = new javax.swing.JLabel();
        pnlPagosAlDia = new javax.swing.JPanel();
        lblNumPagosAlDia = new javax.swing.JLabel();
        lblDescPagosAlDia = new javax.swing.JLabel();
        pnlCasasMorosas = new javax.swing.JPanel();
        lblNumCasasMorosas = new javax.swing.JLabel();
        lblDescCasasMorosas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Vista Verde — Inicio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setBackground(new java.awt.Color(27, 77, 46));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        pnlTarjeta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(58, 107, 53));
        pnlHeader.setPreferredSize(new java.awt.Dimension(750, 65));
        pnlHeader.setLayout(null);

        lblLogo.setBackground(new java.awt.Color(25, 60, 35));
        lblLogo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setText("V");
        lblLogo.setOpaque(true);
        pnlHeader.add(lblLogo);
        lblLogo.setBounds(10, 12, 45, 45);

        lblNombreCondominio.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNombreCondominio.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCondominio.setText("Condominio Vista Verde");
        pnlHeader.add(lblNombreCondominio);
        lblNombreCondominio.setBounds(65, 10, 250, 22);

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(180, 220, 180));
        lblFecha.setText("Mayo 2026 · Miércoles 29");
        pnlHeader.add(lblFecha);
        lblFecha.setBounds(65, 35, 250, 18);

        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);
        pnlHeader.add(btnCerrarSesion);
        btnCerrarSesion.setBounds(590, 20, 130, 34);

        pnlTarjeta.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 70));

        pnlBienvenida.setBackground(new java.awt.Color(214, 237, 220));
        pnlBienvenida.setLayout(null);

        lblAvatarAdmin.setBackground(new java.awt.Color(27, 77, 46));
        lblAvatarAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAvatarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblAvatarAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatarAdmin.setText("AD");
        lblAvatarAdmin.setOpaque(true);
        pnlBienvenida.add(lblAvatarAdmin);
        lblAvatarAdmin.setBounds(10, 5, 30, 30);

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblBienvenida.setText("Bienvenido, Administrador");
        pnlBienvenida.add(lblBienvenida);
        lblBienvenida.setBounds(50, 10, 250, 20);

        pnlTarjeta.add(pnlBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 750, 40));

        lblTituloModulos.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblTituloModulos.setForeground(new java.awt.Color(100, 100, 100));
        lblTituloModulos.setText("MÓDULOS DEL SISTEMA");
        pnlTarjeta.add(lblTituloModulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 120, 200, 18));

        btnRegistroPropietario.setBackground(new java.awt.Color(240, 250, 243));
        btnRegistroPropietario.setText("Registro Propietario");
        btnRegistroPropietario.addActionListener(this::btnRegistroPropietarioActionPerformed);
        pnlTarjeta.add(btnRegistroPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 142, 235, 70));

        btnRegistroPago.setBackground(new java.awt.Color(240, 250, 243));
        btnRegistroPago.setText("Registro de Pago");
        btnRegistroPago.addActionListener(this::btnRegistroPagoActionPerformed);
        pnlTarjeta.add(btnRegistroPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 142, 235, 70));

        btnConfigurarCuota.setBackground(new java.awt.Color(240, 250, 243));
        btnConfigurarCuota.setText("Configurar Cuota");
        btnConfigurarCuota.addActionListener(this::btnConfigurarCuotaActionPerformed);
        pnlTarjeta.add(btnConfigurarCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 142, 235, 70));

        btnEstadoCuenta.setBackground(new java.awt.Color(240, 250, 243));
        btnEstadoCuenta.setText("Estado de Cuenta");
        btnEstadoCuenta.addActionListener(this::btnEstadoCuentaActionPerformed);
        pnlTarjeta.add(btnEstadoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 220, 235, 70));

        btnReporteGeneral.setBackground(new java.awt.Color(240, 250, 243));
        btnReporteGeneral.setText("Reporte General");
        btnReporteGeneral.addActionListener(this::btnReporteGeneralActionPerformed);
        pnlTarjeta.add(btnReporteGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 220, 235, 70));

        btnCasasMorosas.setBackground(new java.awt.Color(200, 50, 50));
        btnCasasMorosas.setText("Casas Morosas");
        pnlTarjeta.add(btnCasasMorosas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 235, 70));

        lblTituloResumen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTituloResumen.setForeground(new java.awt.Color(100, 100, 100));
        lblTituloResumen.setText("RESUMEN DEL MES");
        pnlTarjeta.add(lblTituloResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 330, 200, 18));

        pnlCasasTotales.setLayout(null);

        lblNumCasasTotales.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNumCasasTotales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumCasasTotales.setText("30");
        pnlCasasTotales.add(lblNumCasasTotales);
        lblNumCasasTotales.setBounds(0, 15, 235, 30);

        lblDescCasasTotales.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblDescCasasTotales.setForeground(new java.awt.Color(100, 100, 100));
        lblDescCasasTotales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescCasasTotales.setText("Casas totales");
        pnlCasasTotales.add(lblDescCasasTotales);
        lblDescCasasTotales.setBounds(0, 48, 235, 15);

        pnlTarjeta.add(pnlCasasTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 352, 235, 80));

        pnlPagosAlDia.setLayout(null);

        lblNumPagosAlDia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNumPagosAlDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumPagosAlDia.setText("18");
        pnlPagosAlDia.add(lblNumPagosAlDia);
        lblNumPagosAlDia.setBounds(0, 15, 235, 30);

        lblDescPagosAlDia.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblDescPagosAlDia.setForeground(new java.awt.Color(100, 100, 100));
        lblDescPagosAlDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescPagosAlDia.setText("Pagos al día");
        pnlPagosAlDia.add(lblDescPagosAlDia);
        lblDescPagosAlDia.setBounds(0, 48, 235, 18);

        pnlTarjeta.add(pnlPagosAlDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 352, 235, 80));

        pnlCasasMorosas.setLayout(null);

        lblNumCasasMorosas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNumCasasMorosas.setForeground(new java.awt.Color(200, 50, 50));
        lblNumCasasMorosas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumCasasMorosas.setText("12");
        pnlCasasMorosas.add(lblNumCasasMorosas);
        lblNumCasasMorosas.setBounds(0, 15, 235, 30);

        lblDescCasasMorosas.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblDescCasasMorosas.setForeground(new java.awt.Color(100, 100, 100));
        lblDescCasasMorosas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescCasasMorosas.setText("Casas morosas");
        pnlCasasMorosas.add(lblDescCasasMorosas);
        lblDescCasasMorosas.setBounds(0, 48, 235, 18);

        pnlTarjeta.add(pnlCasasMorosas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 352, 235, 80));

        pnlFondo.add(pnlTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 750, 480));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnRegistroPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPagoActionPerformed
        // TODO add your handling code here:
        new RegistroPago().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroPagoActionPerformed

    private void btnConfigurarCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigurarCuotaActionPerformed
        // TODO add your handling code here:
        new ConfiguracionCuota().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConfigurarCuotaActionPerformed

    private void btnReporteGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteGeneralActionPerformed
        // TODO add your handling code here:
        new reporte_general().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReporteGeneralActionPerformed

    private void btnRegistroPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPropietarioActionPerformed
        // TODO add your handling code here:
        new RegistroPropietario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroPropietarioActionPerformed

    private void btnEstadoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoCuentaActionPerformed
        // TODO add your handling code here:
        new estadoCuenta().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEstadoCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCasasMorosas;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConfigurarCuota;
    private javax.swing.JButton btnEstadoCuenta;
    private javax.swing.JButton btnRegistroPago;
    private javax.swing.JButton btnRegistroPropietario;
    private javax.swing.JButton btnReporteGeneral;
    private javax.swing.JLabel lblAvatarAdmin;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblDescCasasMorosas;
    private javax.swing.JLabel lblDescCasasTotales;
    private javax.swing.JLabel lblDescPagosAlDia;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreCondominio;
    private javax.swing.JLabel lblNumCasasMorosas;
    private javax.swing.JLabel lblNumCasasTotales;
    private javax.swing.JLabel lblNumPagosAlDia;
    private javax.swing.JLabel lblTituloModulos;
    private javax.swing.JLabel lblTituloResumen;
    private javax.swing.JPanel pnlBienvenida;
    private javax.swing.JPanel pnlCasasMorosas;
    private javax.swing.JPanel pnlCasasTotales;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPagosAlDia;
    private javax.swing.JPanel pnlTarjeta;
    // End of variables declaration//GEN-END:variables
}
